# Generated by Django 5.2.14 on 2026-05-27 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 - Direct'), ('scope2', 'Scope 2 - Electricity'), ('scope3', 'Scope 3 - Value Chain')], max_length=20)),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('electricity', 'Electricity'), ('business_travel_flight', 'Business Travel - Flight'), ('business_travel_hotel', 'Business Travel - Hotel'), ('business_travel_ground', 'Business Travel - Ground'), ('procurement', 'Procurement')], max_length=40)),
                ('activity_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('activity_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('original_unit', models.CharField(max_length=50)),
                ('original_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('emission_factor_used', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending_review', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='tenants.organisation')),
            ],
        ),
    ]
