# Generated by Django 5.2.14 on 2026-05-27 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedemission',
            name='source_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emission', to='ingestion.ingestionrow'),
        ),
    ]
