# Generated by Django 5.2.14 on 2026-05-27 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('flag', 'Flagged for Follow-up'), ('edit', 'Edited'), ('lock', 'Locked for Audit')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
