# Generated by Django 5.2.14 on 2026-05-27 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0002_initial'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaction',
            name='analyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='emission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='emissions.normalizedemission'),
        ),
    ]
